-- Generated by scripts/generate-default-model-migration.mjs from public seed data.
-- Fresh installations inherit the owner's public model configuration. Existing
-- installations with any accounts keep administrator names, IDs and pricing.
-- Earlier migrations are immutable; model relations use ON UPDATE CASCADE.
DO $default_models$
BEGIN
  IF NOT EXISTS(SELECT 1 FROM users) THEN
  UPDATE models SET id='gpt-5.6-luna',display_name='gpt-5.6-luna',
    coins_per_call=1,enabled=true,
    stream_chunk_chars=8,stream_delay_ms=20,updated_at=now()
  WHERE id='gpt-5.6-luna' AND NOT is_wisdom_tree AND deleted_at IS NULL;
  UPDATE models SET id='gpt-5.6-sol',display_name='gpt-5.6-sol',
    coins_per_call=2,enabled=true,
    stream_chunk_chars=8,stream_delay_ms=20,updated_at=now()
  WHERE id='gpt-5.6-sol' AND NOT is_wisdom_tree AND deleted_at IS NULL;
  UPDATE models SET id='claude-fable-5.1',display_name='claude-fable-5.1',
    coins_per_call=5,enabled=true,
    stream_chunk_chars=8,stream_delay_ms=20,updated_at=now()
  WHERE id='claude-sonnet-4-6' AND NOT is_wisdom_tree AND deleted_at IS NULL;
  END IF;
END;
$default_models$;
